name: build
on:
  pull_request: {}
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: coursier/cache-action@v8.1
      - uses: coursier/setup-action@v3.0
        with:
          jvm: 17
          apps: sbt scala-cli
      - run: sbt publishLocal
      # Validates the app descriptors, by aggregating them the way the
      # update-channels workflow does (it doesn't check that the files under
      # listings/ are up-to-date, CI updates them upon merge on main)
      - run: scala-cli run .github/scripts/generate-channels.sc
