name: publish
on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

# Releases (on v* tags) and snapshots (on pushes to main) are published to GitHub Packages
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      # the README update below pushes to main
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v7
        with:
          # the publish version is computed from the last tag, which needs the history
          fetch-depth: 0
      - run: git fetch --prune origin main
      - uses: coursier/cache-action@v8
      - uses: coursier/setup-action@v3
        with:
          jvm: 17
      - name: Publish
        run: |
          ./mill --no-daemon mill.javalib.MavenPublishModule/ \
            --publishArtifacts channels.__.publishArtifacts \
            --releaseUri https://maven.pkg.github.com/${{ github.repository }} \
            --snapshotUri https://maven.pkg.github.com/${{ github.repository }}
        env:
          MILL_MAVEN_USERNAME: ${{ github.actor }}
          MILL_MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - run: cs launch scala-cli:1.0.0-RC1 --main-class scala.cli.ScalaCli --jvm 17 -- .github/scripts/generate-readme.sc
        if: startsWith(github.ref, 'refs/tags/')
      - uses: stefanzweifel/git-auto-commit-action@v7.2.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          file_pattern: README.md
          commit_message: Update README.md
          branch: main
          commit_author: Github Actions <actions@github.com>
